<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GamesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('games')->insert([
            [
                'name' => 'Black Myth Wukong',
                'price' => 1120000,
                'sale' => 0,
                'image' => 'add3.jpg',
                'video' => 'Wl05yGSDpxY',
                'short_description' => 'Hắc Thần Thoạiiii',
                'detailed_description' => 'Black Myth Wukong',
                'rating' => 0,
                'views' => 0,
                'tags' => 'w b k',
                'status' => 2,
                'sold' => 0,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Elden Ring',
                'price' => 100000,
                'sale' => 200000,
                'image' => 'eldenring.jpg',
                'video' => 'Djtsw5k_DNc',
                'short_description' => 'abc',
                'detailed_description' => NULL,
                'rating' => 0,
                'views' => 0,
                'tags' => 'e r',
                'status' => 2,
                'sold' => 0,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'God of War Ragnarok',
                'price' => 1200000,
                'sale' => 20,
                'image' => 'gowragnarok.jpg',
                'video' => 'hfJ4Km46A-0',
                'short_description' => 'abc',
                'detailed_description' => NULL,
                'rating' => 0,
                'views' => 0,
                'tags' => 'g o w r',
                'status' => 2,
                'sold' => 0,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cyberpunk 2077: Phantom Liberty',
                'price' => 1000000,
                'sale' => 500000,
                'image' => 'cyberpunk.jpg',
                'video' => 'sJbexcm4Trk',
                'short_description' => 'abc',
                'detailed_description' => '',
                'rating' => 0,
                'views' => 0,
                'tags' => 'c p l',
                'status' => 2,
                'sold' => 0,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hogwarts Legacy',
                'price' => 1250000,
                'sale' => NULL,
                'image' => 'hogwartslegacy.jpg',
                'video' => '1O6Qstncpnc',
                'short_description' => 'abc',
                'detailed_description' => NULL,
                'rating' => 0,
                'views' => 0,
                'tags' => 'h l',
                'status' => 2,
                'sold' => 0,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Starfield',
                'price' => 200000,
                'sale' => NULL,
                'image' => 'starfield.jpg',
                'video' => NULL,
                'short_description' => 'abc',
                'detailed_description' => NULL,
                'rating' => 0,
                'views' => 0,
                'tags' => 's',
                'status' => 2,
                'sold' => 0,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Assassin's Creed Mirage",
                'price' => 1100000,
                'sale' => NULL,
                'image' => 'acmirage.jpg',
                'video' => NULL,
                'short_description' => NULL,
                'detailed_description' => NULL,
                'rating' => 0,
                'views' => 0,
                'tags' => 'a c m',
                'status' => 2,
                'sold' => 0,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Diablo IV',
                'price' => 1300000,
                'sale' => NULL,
                'image' => 'diablo.jpg',
                'video' => NULL,
                'short_description' => NULL,
                'detailed_description' => NULL,
                'rating' => 0,
                'views' => 0,
                'tags' => 'd',
                'status' => 2,
                'sold' => 0,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Resident Evil 4 Remake',
                'price' => 1350000,
                'sale' => NULL,
                'image' => 're4remake.jpeg',
                'video' => NULL,
                'short_description' => 'abc',
                'detailed_description' => NULL,
                'rating' => 0,
                'views' => 0,
                'tags' => 'r e',
                'status' => 2,
                'sold' => 0,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spider-Man 2',
                'price' => 100000,
                'sale' => NULL,
                'image' => 'spiderman2.jpg',
                'video' => NULL,
                'short_description' => NULL,
                'detailed_description' => NULL,
                'rating' => 0,
                'views' => 0,
                'tags' => 's m',
                'status' => 2,
                'sold' => 0,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Street Fighter 6',
                'price' => 1250000,
                'sale' => NULL,
                'image' => 'sf6.jpg',
                'video' => NULL,
                'short_description' => NULL,
                'detailed_description' => NULL,
                'rating' => 0,
                'views' => 0,
                'tags' => 's f',
                'status' => 2,
                'sold' => 0,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Last of Us Part I',
                'price' => 1400000,
                'sale' => NULL,
                'image' => 'tloupart1.jpeg',
                'video' => NULL,
                'short_description' => NULL,
                'detailed_description' => NULL,
                'rating' => 0,
                'views' => 0,
                'tags' => 't l o u',
                'status' => 2,
                'sold' => 0,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
