<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GamesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('games')->insert([
            [
                'name' => 'Monster Hunter Wilds',
                'price' => 1120000,
                'sale' => 0,
                'image' => 'monsterhunterwilds.jpg',
                'video' => 'CapcomVideoID', // Thay bằng ID video YouTube nếu có
                'short_description' => 'Săn quái vật đỉnh cao',
                'detailed_description' => 'Monster Hunter Wilds là tựa game hành động nhập vai mới nhất từ Capcom, mang đến trải nghiệm săn quái vật hoành tráng.',
                'rating' => 0,
                'views' => 0,
                'tags' => 'm h w',
                'status' => 1,
                'sold' => 0,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Split Fiction',
                'price' => 100000,
                'sale' => 200000,
                'image' => 'splitfiction.jpg',
                'video' => 'HazelightVideoID', // Thay bằng ID video YouTube nếu có
                'short_description' => 'Hành trình hợp tác',
                'detailed_description' => 'Split Fiction là game co-op từ Hazelight Studios, nơi hai người chơi cùng nhau vượt qua các thế giới khoa học viễn tưởng và giả tưởng.',
                'rating' => 0,
                'views' => 0,
                'tags' => 's f',
                'status' => 1,
                'sold' => 0,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Assassin’s Creed Shadows',
                'price' => 1200000,
                'sale' => 20,
                'image' => 'assassinscreedshadows.jpg',
                'video' => 'UbisoftVideoID', // Thay bằng ID video YouTube nếu có
                'short_description' => 'Nhật Bản thời phong kiến',
                'detailed_description' => 'Assassin’s Creed Shadows đưa người chơi đến Nhật Bản thời phong kiến với hai nhân vật chính: một shinobi và một samurai.',
                'rating' => 0,
                'views' => 0,
                'tags' => 'a c s',
                'status' => 1,
                'sold' => 0,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Borderlands 4',
                'price' => 1000000,
                'sale' => 500000,
                'image' => 'borderlands4.jpg',
                'video' => 'GearboxVideoID', // Thay bằng ID video YouTube nếu có
                'short_description' => 'Bắn súng cướp bóc',
                'detailed_description' => 'Borderlands 4 đưa người chơi đến hành tinh Kairos với hàng tỷ vũ khí và lối chơi co-op điên rồ.',
                'rating' => 0,
                'views' => 0,
                'tags' => 'b number',
                'status' => 1,
                'sold' => 0,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Civilization VII',
                'price' => 1250000,
                'sale' => NULL,
                'image' => 'civilization7.jpg',
                'video' => 'FiraxisVideoID', // Thay bằng ID video YouTube nếu có
                'short_description' => 'Chiến lược đỉnh cao',
                'detailed_description' => 'Civilization VII mang đến trải nghiệm chiến lược 4X với hệ thống thời đại mới và tùy chỉnh nền văn minh.',
                'rating' => 0,
                'views' => 0,
                'tags' => 'c number',
                'status' => 1,
                'sold' => 0,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Metroid Prime 4: Beyond',
                'price' => 200000,
                'sale' => NULL,
                'image' => 'metroidprime4.jpg',
                'video' => NULL,
                'short_description' => 'Thám hiểm không gian',
                'detailed_description' => 'Metroid Prime 4: Beyond là tựa game FPS phiêu lưu mới nhất của Nintendo, nơi Samus Aran đối đầu với cướp biển không gian.',
                'rating' => 0,
                'views' => 0,
                'tags' => 'm p number',
                'status' => 1,
                'sold' => 0,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Death Stranding 2: On the Beach',
                'price' => 1100000,
                'sale' => NULL,
                'image' => 'deathstranding2.jpg',
                'video' => NULL,
                'short_description' => 'Giao hàng kỳ lạ',
                'detailed_description' => 'Death Stranding 2: On the Beach tiếp tục câu chuyện của Hideo Kojima với những yếu tố kỳ bí và giao hàng độc đáo.',
                'rating' => 0,
                'views' => 0,
                'tags' => 'd s number',
                'status' => 1,
                'sold' => 0,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kingdom Come: Deliverance 2',
                'price' => 1300000,
                'sale' => NULL,
                'image' => 'kingdomcome2.jpg',
                'video' => NULL,
                'short_description' => 'Trung cổ chân thực',
                'detailed_description' => 'Kingdom Come: Deliverance 2 là game nhập vai trung cổ với cốt truyện hấp dẫn và chiến đấu chân thực.',
                'rating' => 0,
                'views' => 0,
                'tags' => 'k c d number',
                'status' => 1,
                'sold' => 0,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Elden Ring: Nightreign',
                'price' => 1350000,
                'sale' => NULL,
                'image' => 'eldenringnightreign.jpg',
                'video' => NULL,
                'short_description' => 'Sinh tồn co-op',
                'detailed_description' => 'Elden Ring: Nightreign là phiên bản co-op của Elden Ring, nơi người chơi sinh tồn qua ba đêm trong thế giới Limgrave.',
                'rating' => 0,
                'views' => 0,
                'tags' => 'e r n',
                'status' => 1,
                'sold' => 0,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Like a Dragon: Pirate Yakuza in Hawaii',
                'price' => 100000,
                'sale' => NULL,
                'image' => 'likeadragonpirate.jpg',
                'video' => NULL,
                'short_description' => 'Cướp biển hiện đại',
                'detailed_description' => 'Like a Dragon: Pirate Yakuza in Hawaii đưa Goro Majima vào vai một tên cướp biển hiện đại với lối chơi đánh đấm và phiêu lưu.',
                'rating' => 0,
                'views' => 0,
                'tags' => 'l a d p',
                'status' => 1,
                'sold' => 0,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fable',
                'price' => 1250000,
                'sale' => NULL,
                'image' => 'fable.jpg',
                'video' => NULL,
                'short_description' => 'Thế giới giả tưởng',
                'detailed_description' => 'Fable trở lại với thế giới giả tưởng Albion, nơi lựa chọn của bạn định hình câu chuyện và nhân vật.',
                'rating' => 0,
                'views' => 0,
                'tags' => 'f',
                'status' => 1,
                'sold' => 0,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Doom: The Dark Ages',
                'price' => 1400000,
                'sale' => NULL,
                'image' => 'doomdarkages.jpg',
                'video' => NULL,
                'short_description' => 'Hành động điên cuồng',
                'detailed_description' => 'Doom: The Dark Ages là tựa game hành động bắn súng với bối cảnh trung cổ công nghệ, nơi bạn tiêu diệt quỷ dữ.',
                'rating' => 0,
                'views' => 0,
                'tags' => 'd d a',
                'status' => 1,
                'sold' => 0,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
